filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php:
            version: 7.4
        postgresql: false
        redis: false
    dependencies:
        override:
            - 'composer install --prefer-source'